
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "53ba6007-63e0-4ca9-ac52-6739b215834d"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "05e3f336-770f-4747-8ffd-a9b666bf5706 ",
    "account_id_to": "a7573efa-3053-4b86-9ece-db7cb18d0d39",
    "amount": 100
}