
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "teste Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "53ba6007-63e0-4ca9-ac52-6739b215834d"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "3c79aede-12a4-4f65-9307-6d4d1a35b1c8",
    "account_id_to": "f1e4b8b2-6a44-4d5b-83e8-111c8f4dcbeb",
    "amount": 100
}