
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "a04fe9e9-b107-419d-a143-d2bab31370c6"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "5aec21ad-8528-49e4-b7f9-2495882930b7 ",
    "account_id_to": "be3fb37f-a234-4f6c-ae1f-06d589bcd30f",
    "amount": 100
}